Add files for Review
jugosack/To_Do_list_Review pull request #1
Opened 2023-01-23 22:31 UTC by jugosack

2023-01-23 22:41 UTC, biruk-bereka requested changes
Hi @jugosack, 
Good job so far 👍🏼
There are some issues that you still need to work on to  make your code clean and follow JS best practices:
   - Please check the inline comments below and make required changes.
   - Please put all JS files except for index.js file in modules folder inside src folder. 
   - Fell free to contact me for any questions.

2023-01-23 22:41 UTC, biruk-bereka commented on src/todo.js
> +}
Kindly use one of the methods above. Since both methods set data to local storage. Make changes for files that use these methods.

2023-01-23 22:41 UTC, biruk-bereka commented on src/storage.js
> +export default data;
Great using one JS file for local storage function. What do you think about adding a method for setting data to local storage in this file?

2023-01-23 22:54 UTC, jugosack commented on src/todo.js
> +}
@biruk-bereka Thank you for your comment.🤝😀

2023-01-23 22:55 UTC, jugosack commented on src/storage.js
> +export default data;
@biruk-bereka Thanks for the direction. I will try to follow your suggestion.👍😀

2023-01-27 19:32 UTC, biruk-bereka approved these changes
## Hello @jugosack        :wave: ,
I am Biruk your reviewer for this PR :man_beard:  

Thank you for meeting all the project requirements good job! :partying_face: 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! :partying_face: 🎉 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️ 
 Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@biruk-bereka** in your question so I can receive the notification.

2023-01-27 19:33 UTC, merged